language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 7b1f606d-2391-46ea-9daa-ce2ac323d419
  app: safe-castle-59515
  on:
    repo: jao05/node-restaurants-app-mongoose
    branch: feature/with-tests
